- name: create user {{ automysqlbackup_default_cron_user }}
  user:
    name: '{{ automysqlbackup_default_cron_user }}'
    group: '{{ automysqlbackup_default_cron_group }}'
    system: true
    home: '{{ automysqlbackup_backupdir }}'
  when: automysqlbackup_create_user

- name: Create .ssh folder
  file:
    dest: '{{ automysqlbackup_backupdir }}/.ssh'
    mode: '0750'
    state: directory
    owner: '{{ automysqlbackup_default_cron_user }}'
- name: Generate a ssh key for {{ automysqlbackup_default_cron_user }}
  openssh_keypair:
    path: '{{ automysqlbackup_backupdir }}/.ssh/id_ed25519'
    type: ed25519
    size: 521
    state: present
    force: no
    owner: '{{ automysqlbackup_default_cron_user }}'
    comment: 'automysqlbackup key {{ ansible_hostname }}'
  when: automysqlbackup_create_user

- name: create the differents configurations and credentials files
  include_tasks: configuration-server.yml
  loop: '{{ automysqlbackup_configurations }}'
  loop_control:
    loop_var: automysqlbackup_current_configuration
    label: "{{ automysqlbackup_current_configuration.name }}"
- name: create cron file
  template:
    src: cron.j2
    dest: '{{ automysqlbackup_default_cron_path }}/automysqlbackup'